# ============================================================
#  i) Configuración del Name Server (rmiregistry) - SERVIDOR
# ============================================================
# Dirección IP donde se encuentra el rmiregistry (NS).
# Si todo corre en el mismo PC deje "localhost".
# Si corre en red, ponga la IP de este PC (ej: 192.168.1.10).
ns.ip=localhost

# Puerto por el que escucha el rmiregistry
ns.puerto=2020

# (Opcional, solo en red) IP de este PC que se anuncia en las referencias remotas.
# Si se deja vacío el servidor usa el valor de ns.ip.
rmi.hostname=
