# ============================================================
#  i) Configuración del Name Server (rmiregistry) - CLIENTE
# ============================================================
# Dirección IP del PC donde se encuentra el rmiregistry (NS) / servidor de chat.
# Si todo corre en el mismo PC deje "localhost".
ns.ip=localhost

# Puerto por el que escucha el rmiregistry (debe ser el mismo del servidor)
ns.puerto=2020

# (Opcional, solo en red) IP de ESTE PC cliente, para que el servidor pueda
# hacer el callback. Déjelo vacío si todo corre en el mismo PC.
rmi.hostname=
